#!/usr/bin/python

# Generate semantic version number from commit history
#
# HP Dumm
#
# 2025-09-05
#
# See: https://www.conventionalcommits.org

import subprocess
import re

# counters
major = 0
minor = 0
fix = 0

# regex
fix_pattern = re.compile(r"\w*\sfix(\(.*\))?:")
minor_pattern = re.compile(r"\w*\sfeat(\(.*\))?:")
major_pattern = re.compile(r"!:")

# loop
log_text = subprocess.check_output(["git", "log", "--oneline"]).decode("utf-8")
for line in reversed(log_text.split("\n")):
  if fix_pattern.match(line):
    fix += 1
  elif minor_pattern.match(line):
    fix = 0
    minor += 1
  elif major_pattern.search(line):
    fix = 0
    minor = 0
    major += 1

# output
print(f"{major}.{minor}.{fix}")
